-- Insert data into Winery table
INSERT INTO Winery (Name, Region, Country) VALUES
('Robert Mondavi Winery', 'Napa Valley', 'USA'),
('Silver Oak Cellars', 'Napa Valley', 'USA'),
('Château Margaux', 'Bordeaux', 'France'),
('Penfolds', 'Barossa Valley', 'Australia'),
('Antinori', 'Tuscany', 'Italy'),
('Concha y Toro', 'Maipo Valley', 'Chile'),
('Beringer Vineyards', 'Napa Valley', 'USA'),
('Duckhorn Vineyards', 'Napa Valley', 'USA'),
('Veuve Clicquot', 'Champagne', 'France'),
('Moët & Chandon', 'Champagne', 'France'),
('Villa Maria', 'Marlborough', 'New Zealand'),
('Louis Roederer', 'Champagne', 'France'),
('Catena Zapata', 'Mendoza', 'Argentina'),
('Ridge Vineyards', 'Santa Cruz Mountains', 'USA'),
('Torres', 'Penedès', 'Spain'),
('Domaine de la Romanée-Conti', 'Burgundy', 'France'),
('Barossa Valley Estate', 'Barossa Valley', 'Australia'),
('Clos Apalta', 'Colchagua Valley', 'Chile'),
('Cloudy Bay', 'Marlborough', 'New Zealand'),
('Marchesi di Barolo', 'Piedmont', 'Italy'),
('Ornellaia', 'Tuscany', 'Italy'),
('Chateau Ste. Michelle', 'Washington', 'USA'),
('Henschke', 'Eden Valley', 'Australia'),
('E. Guigal', 'Rhône Valley', 'France'),
('Mission Hill Family Estate', 'Okanagan Valley', 'Canada'),
('Inniskillin', 'Niagara Peninsula', 'Canada'),
('Jackson-Triggs', 'Niagara Peninsula', 'Canada'),
('Tinhorn Creek Vineyards', 'Okanagan Valley', 'Canada'),
('Cave Spring Cellars', 'Niagara Peninsula', 'Canada');