-- Insert additional sample data into Wine table
INSERT INTO Wine (Name, Type, Color, Price, Rating, Description, WineryID) VALUES
('Robert Mondavi Winery Fumé Blanc', 'Sauvignon Blanc', 'White', 18.99, 4, 'A crisp and refreshing white wine.', 1),
('Robert Mondavi Winery Merlot', 'Merlot', 'Red', 22.99, 4, 'A smooth and fruity red wine.', 1),
('Silver Oak Cellars Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 69.99, 5, 'A rich and robust red wine.', 2),
('Silver Oak Cellars Chardonnay', 'Chardonnay', 'White', 27.99, 4, 'A buttery and rich white wine.', 2),
('Château Margaux Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 50.99, 5, 'A premium red wine with deep flavors.', 3),
('Château Margaux Chardonnay', 'Chardonnay', 'White', 39.99, 4, 'A refined and elegant white wine.', 3),
('Penfolds Grange', 'Shiraz', 'Red', 399.99, 5, 'An exquisite Shiraz with complex flavors.', 4),
('Penfolds Bin 389', 'Cabernet Shiraz', 'Red', 69.99, 5, 'A rich blend of Cabernet and Shiraz.', 4),
('Antinori Tignanello', 'Red Blend', 'Red', 149.99, 5, 'A luxurious red blend with depth and complexity.', 5),
('Antinori Solaia', 'Red Blend', 'Red', 249.99, 5, 'A prestigious red blend with rich flavors.', 5),
('Concha y Toro Don Melchor', 'Cabernet Sauvignon', 'Red', 89.99, 5, 'A bold and flavorful Cabernet Sauvignon.', 6),
('Concha y Toro Gran Reserva Serie Riberas', 'Malbec', 'Red', 29.99, 4, 'A smooth and aromatic Malbec.', 6),
('Beringer Vineyards Private Reserve Chardonnay', 'Chardonnay', 'White', 39.99, 5, 'A premium Chardonnay with complex flavors.', 7),
('Beringer Vineyards Knight Valley Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 54.99, 5, 'A rich and robust Cabernet Sauvignon.', 7),
('Duckhorn Vineyards Merlot', 'Merlot', 'Red', 39.99, 5, 'A smooth and velvety Merlot.', 8),
('Duckhorn Vineyards Sauvignon Blanc', 'Sauvignon Blanc', 'White', 19.99, 4, 'A vibrant and aromatic Sauvignon Blanc.', 8),
('Veuve Clicquot Rosé Champagne', 'Champagne', 'Sparkling', 64.99, 5, 'A delicate and elegant Rosé Champagne.', 9),
('Veuve Clicquot Vintage Brut', 'Champagne', 'Sparkling', 79.99, 5, 'A fine Vintage Champagne with rich flavors.', 9),
('Moët & Chandon Rosé Impérial', 'Champagne', 'Sparkling', 57.99, 5, 'A refreshing Rosé Champagne with vibrant flavors.', 10),
('Moët & Chandon Grand Vintage', 'Champagne', 'Sparkling', 89.99, 5, 'A luxurious Grand Vintage Champagne.', 10),
('Villa Maria Private Bin Chardonnay', 'Chardonnay', 'White', 19.99, 4, 'A crisp and refreshing Chardonnay.', 11),
('Villa Maria Reserve Sauvignon Blanc', 'Sauvignon Blanc', 'White', 29.99, 5, 'A premium Sauvignon Blanc with complex flavors.', 11),
('Louis Roederer Brut Premier', 'Champagne', 'Sparkling', 49.99, 5, 'A classic Brut Champagne with rich flavor.', 12),
('Louis Roederer Blanc de Blancs', 'Champagne', 'Sparkling', 89.99, 5, 'A fine Blanc de Blancs Champagne.', 12),
('Catena Zapata Adrianna Vineyard Malbec', 'Malbec', 'Red', 129.99, 5, 'An exquisite Malbec with complex flavors.', 13),
('Catena Zapata White Stones Chardonnay', 'Chardonnay', 'White', 99.99, 5, 'A premium Chardonnay with rich flavor.', 13),
('Ridge Vineyards Geyserville', 'Red Blend', 'Red', 44.99, 5, 'A smooth and fruity red blend.', 14),
('Ridge Vineyards Lytton Springs', 'Zinfandel', 'Red', 44.99, 5, 'A bold and spicy Zinfandel.', 14),
('Torres Viña Sol', 'White Blend', 'White', 11.99, 4, 'A crisp and refreshing white blend.', 15),
('Torres Gran Coronas', 'Cabernet Sauvignon', 'Red', 19.99, 4, 'A rich and robust Cabernet Sauvignon.', 15),
('Domaine de la Romanée-Conti Romanée-Conti', 'Pinot Noir', 'Red', 4000.99, 5, 'An exquisite Pinot Noir with complex flavors.', 16),
('Domaine de la Romanée-Conti Richebourg', 'Pinot Noir', 'Red', 3500.99, 5, 'A prestigious Pinot Noir with rich flavors.', 16),
('Barossa Valley Estate Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 19.99, 4, 'A robust and spicy Cabernet Sauvignon.', 17),
('Barossa Valley Estate Merlot', 'Merlot', 'Red', 17.99, 4, 'A smooth and fruity Merlot.', 17),
('Clos Apalta Apalta Vineyard', 'Red Blend', 'Red', 129.99, 5, 'An elegant red blend with complex flavors.', 18),
('Clos Apalta Casa Lapostolle', 'Merlot', 'Red', 24.99, 4, 'A smooth and fruity Merlot.', 18),
('Cloudy Bay Chardonnay', 'Chardonnay', 'White', 27.99, 4, 'A crisp and refreshing Chardonnay.', 19),
('Cloudy Bay Te Koko', 'Sauvignon Blanc', 'White', 44.99, 5, 'A refined and aromatic Sauvignon Blanc.', 19),
('Marchesi di Barolo Barbera Alba', 'Barbera', 'Red', 19.99, 4, 'A rich and robust Barbera.', 20),
('Marchesi di Barolo Gavi', 'Cortese', 'White', 14.99, 4, 'A crisp and refreshing Gavi.', 20),
('Ornellaia Le Volte', 'Red Blend', 'Red', 34.99, 5, 'A smooth and velvety red blend.', 21),
('Ornellaia Poggio alle Gazze', 'Sauvignon Blanc', 'White', 44.99, 5, 'A refined and aromatic Sauvignon Blanc.', 21),
('Chateau Ste. Michelle Merlot', 'Merlot', 'Red', 14.99, 4, 'A smooth and fruity Merlot.', 22),
('Chateau Ste. Michelle Riesling', 'Riesling', 'White', 9.99, 4, 'A crisp and aromatic Riesling.', 22),
('Henschke Mount Edelstone', 'Shiraz', 'Red', 129.99, 5, 'An exquisite Shiraz with complex flavors.', 23),
('Henschke Julius Riesling', 'Riesling', 'White', 39.99, 5, 'A refined and aromatic Riesling.', 23),
('E. Guigal Hermitage', 'Syrah', 'Red', 69.99, 5, 'A rich and robust Syrah.', 24),
('E. Guigal Condrieu', 'Viognier', 'White', 59.99, 5, 'A crisp and aromatic Viognier.', 24),
('Mission Hill Family Estate Compendium', 'Red Blend', 'Red', 59.99, 5, 'A sophisticated red blend with rich flavors.', 25),
('Mission Hill Family Estate Perpetua', 'Chardonnay', 'White', 39.99, 5, 'A premium Chardonnay with complex flavors.', 25),
('Inniskillin Riesling Icewine', 'Icewine', 'White', 59.99, 5, 'A sweet and luscious dessert wine.', 26),
('Inniskillin Cabernet Franc Icewine', 'Icewine', 'Red', 69.99, 5, 'A unique and flavorful dessert wine.', 26),
('Jackson-Triggs Grand Reserve Merlot', 'Merlot', 'Red', 24.99, 4, 'A smooth and fruity Merlot.', 27),
('Jackson-Triggs Grand Reserve Chardonnay', 'Chardonnay', 'White', 19.99, 4, 'A buttery and rich Chardonnay.', 27),
('Tinhorn Creek Gewürztraminer', 'Gewürztraminer', 'White', 17.99, 4, 'A vibrant and aromatic Gewürztraminer.', 28),
('Tinhorn Creek Pinot Gris', 'Pinot Gris', 'White', 19.99, 4, 'A crisp and refreshing Pinot Gris.', 28),
('Cave Spring Cellars Cabernet Franc', 'Cabernet Franc', 'Red', 24.99, 4, 'A rich and robust Cabernet Franc.', 29),
('Cave Spring Cellars Chardonnay Musqué', 'Chardonnay', 'White', 21.99, 4, 'A unique and aromatic Chardonnay.', 29),
-- Add 50 more wine records to reach the additional 100
('Robert Mondavi Winery Cabernet Franc', 'Cabernet Franc', 'Red', 32.99, 4, 'A rich and robust Cabernet Franc.', 1),
('Robert Mondavi Winery Zinfandel', 'Zinfandel', 'Red', 29.99, 4, 'A fruity and spicy Zinfandel.', 1),
('Silver Oak Cellars Merlot', 'Merlot', 'Red', 36.99, 4, 'A smooth and velvety Merlot.', 2),
('Silver Oak Cellars Sauvignon Blanc', 'Sauvignon Blanc', 'White', 24.99, 4, 'A vibrant and aromatic Sauvignon Blanc.', 2),
('Château Margaux Syrah', 'Syrah', 'Red', 52.99, 5, 'A bold and flavorful Syrah.', 3),
('Château Margaux Pinot Noir', 'Pinot Noir', 'Red', 49.99, 5, 'A refined and elegant Pinot Noir.', 3),
('Penfolds Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 31.99, 4, 'A rich and robust Cabernet Sauvignon.', 4),
('Penfolds Chardonnay', 'Chardonnay', 'White', 26.99, 4, 'A buttery and rich Chardonnay.', 4),
('Antinori Vermentino', 'Vermentino', 'White', 19.99, 4, 'A crisp and refreshing Vermentino.', 5),
('Antinori Brunello di Montalcino', 'Brunello', 'Red', 55.99, 5, 'A full-bodied and complex Brunello.', 5),
('Concha y Toro Chardonnay', 'Chardonnay', 'White', 18.99, 4, 'A vibrant and aromatic Chardonnay.', 6),
('Concha y Toro Merlot', 'Merlot', 'Red', 20.99, 4, 'A smooth and fruity Merlot.', 6),
('Beringer Vineyards Pinot Noir', 'Pinot Noir', 'Red', 34.99, 5, 'A refined and elegant Pinot Noir.', 7),
('Beringer Vineyards Sauvignon Blanc', 'Sauvignon Blanc', 'White', 22.99, 4, 'A crisp and refreshing Sauvignon Blanc.', 7),
('Duckhorn Vineyards Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 42.99, 5, 'A rich and robust Cabernet Sauvignon.', 8),
('Duckhorn Vineyards Pinot Noir', 'Pinot Noir', 'Red', 38.99, 4, 'A smooth and balanced Pinot Noir.', 8),
('Veuve Clicquot Demi-Sec', 'Champagne', 'Sparkling', 54.99, 5, 'A semi-sweet Champagne with rich flavors.', 9),
('Veuve Clicquot Extra Brut Extra Old', 'Champagne', 'Sparkling', 99.99, 5, 'A refined and elegant Extra Brut Champagne.', 9),
('Moët & Chandon Nectar Impérial', 'Champagne', 'Sparkling', 64.99, 5, 'A sweet and luscious Champagne.', 10),
('Moët & Chandon Ice Impérial', 'Champagne', 'Sparkling', 64.99, 5, 'A refreshing Champagne served over ice.', 10),
('Villa Maria Pinot Noir', 'Pinot Noir', 'Red', 22.99, 4, 'A smooth and balanced Pinot Noir.', 11),
('Villa Maria Gewürztraminer', 'Gewürztraminer', 'White', 19.99, 4, 'A vibrant and aromatic Gewürztraminer.', 11),
('Louis Roederer Vintage Brut', 'Champagne', 'Sparkling', 79.99, 5, 'A luxurious Vintage Brut Champagne.', 12),
('Louis Roederer Carte Blanche Demi-Sec', 'Champagne', 'Sparkling', 69.99, 5, 'A semi-sweet Champagne with rich flavors.', 12),
('Catena Zapata Cabernet Franc', 'Cabernet Franc', 'Red', 59.99, 5, 'A refined and aromatic Cabernet Franc.', 13),
('Catena Zapata Nicasia Vineyard Malbec', 'Malbec', 'Red', 69.99, 5, 'A bold and flavorful Malbec.', 13),
('Ridge Vineyards East Bench Zinfandel', 'Zinfandel', 'Red', 34.99, 5, 'A fruity and spicy Zinfandel.', 14),
('Ridge Vineyards Estate Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 64.99, 5, 'A rich and robust Cabernet Sauvignon.', 14),
('Torres Celeste Crianza', 'Tempranillo', 'Red', 19.99, 4, 'A smooth and fruity Tempranillo.', 15),
('Torres Vina Esmeralda', 'White Blend', 'White', 11.99, 4, 'A crisp and aromatic white blend.', 15),
('Domaine de la Romanée-Conti Montrachet', 'Chardonnay', 'White', 5000.99, 5, 'An exquisite Chardonnay with complex flavors.', 16),
('Domaine de la Romanée-Conti Échezeaux', 'Pinot Noir', 'Red', 3300.99, 5, 'A prestigious Pinot Noir with rich flavors.', 16),
('Barossa Valley Estate Grenache Shiraz Mourvèdre', 'Red Blend', 'Red', 18.99, 4, 'A bold and spicy red blend.', 17),
('Barossa Valley Estate Shiraz Cabernet', 'Red Blend', 'Red', 20.99, 4, 'A robust and flavorful red blend.', 17),
('Clos Apalta Petit Clos', 'Red Blend', 'Red', 44.99, 4, 'A refined and aromatic red blend.', 18),
('Clos Apalta Sauvignon Blanc', 'Sauvignon Blanc', 'White', 17.99, 4, 'A vibrant and aromatic Sauvignon Blanc.', 18),
('Cloudy Bay Te Wahi', 'Pinot Noir', 'Red', 59.99, 5, 'A smooth and balanced Pinot Noir.', 19),
('Cloudy Bay Gewürztraminer', 'Gewürztraminer', 'White', 24.99, 4, 'A vibrant and aromatic Gewürztraminer.', 19),
('Marchesi di Barolo Dolcetto Alba', 'Dolcetto', 'Red', 17.99, 4, 'A smooth and fruity Dolcetto.', 20),
('Marchesi di Barolo Moscato Asti', 'Moscato', 'White', 14.99, 4, 'A sweet and refreshing Moscato.', 20),
('Ornellaia Le Serre Nuove', 'Red Blend', 'Red', 59.99, 5, 'A refined and elegant red blend.', 21),
('Ornellaia Masseto', 'Merlot', 'Red', 699.99, 5, 'A luxurious and complex Merlot.', 21),
('Chateau Ste. Michelle Chardonnay', 'Chardonnay', 'White', 12.99, 4, 'A crisp and refreshing Chardonnay.', 22),
('Chateau Ste. Michelle Sauvignon Blanc', 'Sauvignon Blanc', 'White', 11.99, 4, 'A vibrant and aromatic Sauvignon Blanc.', 22),
('Henschke Keyneton Euphonium', 'Red Blend', 'Red', 49.99, 5, 'A rich and robust red blend.', 23),
('Henschke Tillys Vineyard', 'White Blend', 'White', 24.99, 4, 'A crisp and aromatic white blend.', 23),
('E. Guigal St. Joseph', 'Syrah', 'Red', 29.99, 4, 'A smooth and fruity Syrah.', 24),
('E. Guigal Crozes-Hermitage', 'Syrah', 'Red', 27.99, 4, 'A bold and spicy Syrah.', 24),
('Mission Hill Family Estate Prospectus', 'Red Blend', 'Red', 99.99, 5, 'A sophisticated red blend with rich flavors.', 25),
('Mission Hill Family Estate Quatrain', 'Red Blend', 'Red', 79.99, 5, 'A refined and elegant red blend.', 25),
('Inniskillin Icewine Riesling', 'Icewine', 'White', 59.99, 5, 'A sweet and luscious dessert wine.', 26),
('Inniskillin Late Autumn Riesling', 'Riesling', 'White', 21.99, 4, 'A crisp and aromatic Riesling.', 26),
('Jackson-Triggs Grand Reserve Pinot Noir', 'Pinot Noir', 'Red', 29.99, 4, 'A refined and elegant Pinot Noir.', 27),
('Jackson-Triggs Grand Reserve Sauvignon Blanc', 'Sauvignon Blanc', 'White', 19.99, 4, 'A vibrant and aromatic Sauvignon Blanc.', 27),
('Tinhorn Creek Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 27.99, 4, 'A rich and robust Cabernet Sauvignon.', 28),
('Tinhorn Creek Syrah', 'Syrah', 'Red', 26.99, 4, 'A bold and spicy Syrah.', 28),
('Cave Spring Cellars Gamay', 'Gamay', 'Red', 18.99, 4, 'A smooth and fruity Gamay.', 29),
('Cave Spring Cellars Blanc de Blancs', 'Chardonnay', 'White', 24.99, 4, 'A crisp and refreshing Chardonnay.', 29),
('Robert Mondavi Winery Cabernet', 'Cabernet', 'Red', 25.99, 5, 'A rich and robust red wine.', 1),
('Silver Oak Cellars Pinot Grigio', 'Pinot Grigio', 'White', 19.99, 4, 'A crisp and refreshing white wine.', 2),
('Château Margaux Merlot', 'Merlot', 'Red', 45.99, 5, 'A smooth and velvety red wine.', 3),
('Penfolds Shiraz', 'Shiraz', 'Red', 29.99, 4, 'A spicy and bold red wine.', 4),
('Antinori Chianti', 'Chianti', 'Red', 22.99, 4, 'A classic Italian red wine.', 5),
('Concha y Toro Sauvignon Blanc', 'Sauvignon Blanc', 'White', 17.99, 4, 'A zesty and aromatic white wine.', 6),
('Beringer Vineyards Zinfandel', 'Zinfandel', 'Red', 24.99, 5, 'A fruity and spicy red wine.', 7),
('Duckhorn Vineyards Chardonnay', 'Chardonnay', 'White', 27.99, 4, 'A buttery and rich white wine.', 8),
('Veuve Clicquot Yellow Label Brut', 'Champagne', 'Sparkling', 49.99, 5, 'A classic Champagne with rich flavor.', 9),
('Moët & Chandon Impérial Brut', 'Champagne', 'Sparkling', 47.99, 5, 'A fine Champagne with a refreshing finish.', 10),
('Villa Maria Sauvignon Blanc', 'Sauvignon Blanc', 'White', 16.99, 4, 'A vibrant and aromatic white wine.', 11),
('Louis Roederer Cristal Brut', 'Champagne', 'Sparkling', 199.99, 5, 'An exquisite Champagne with complex flavors.', 12),
('Catena Zapata Malbec', 'Malbec', 'Red', 21.99, 4, 'A bold and flavorful red wine.', 13),
('Ridge Vineyards Monte Bello', 'Cabernet Sauvignon', 'Red', 150.99, 5, 'A premium red wine with deep flavors.', 14),
('Torres Sangre de Toro', 'Red Blend', 'Red', 14.99, 4, 'A smooth and fruity red wine.', 15),
('Domaine de la Romanée-Conti La Tâche', 'Pinot Noir', 'Red', 3500.99, 5, 'A prestigious red wine with rich flavors.', 16),
('Barossa Valley Estate Shiraz', 'Shiraz', 'Red', 19.99, 4, 'A robust and spicy red wine.', 17),
('Clos Apalta Le Petit Clos', 'Red Blend', 'Red', 69.99, 5, 'A refined red wine with elegant flavors.', 18),
('Cloudy Bay Pinot Noir', 'Pinot Noir', 'Red', 34.99, 4, 'A smooth and balanced red wine.', 19),
('Marchesi di Barolo Barolo', 'Barolo', 'Red', 45.99, 5, 'A full-bodied and complex red wine.', 20),
('Ornellaia Bolgheri Superiore', 'Red Blend', 'Red', 249.99, 5, 'A luxurious red wine with depth and complexity.', 21),
('Chateau Ste. Michelle Cabernet Sauvignon', 'Cabernet Sauvignon', 'Red', 16.99, 4, 'A rich and flavorful red wine.', 22),
('Henschke Hill of Grace', 'Shiraz', 'Red', 699.99, 5, 'A legendary red wine with profound flavors.', 23),
('E. Guigal Côte-Rôtie', 'Syrah', 'Red', 79.99, 5, 'An elegant red wine with complex aromas.', 24),
('Mission Hill Oculus', 'Red Blend', 'Red', 80.99, 5, 'A sophisticated red wine with rich flavors.', 25),
('Inniskillin Icewine Vidal', 'Icewine', 'White', 49.99, 5, 'A sweet and luscious dessert wine.', 26),
('Jackson-Triggs Grand Reserve Shiraz', 'Shiraz', 'Red', 29.99, 4, 'A bold and spicy red wine.', 27),
('Tinhorn Creek Merlot', 'Merlot', 'Red', 24.99, 4, 'A smooth and fruity red wine.', 28),
('Cave Spring Cellars Riesling', 'Riesling', 'White', 19.99, 4, 'A crisp and aromatic white wine.', 29);