-- Update Logos For Tables

UPDATE wine
SET logo = CASE
    WHEN winery = 'Antinori' THEN '/images/villa-antinori.png'
    WHEN winery = 'Henschke' THEN '/images/henschke.png'
    WHEN winery = 'Mission Hill' THEN '/images/missionhill.png'
    WHEN winery = 'Barossa Valley Estate' THEN '/images/barossa_valley_estate.png'
    WHEN winery = 'Veuve Clicquot' THEN '/images/Veuve-clicquot.png'
    WHEN winery = 'Moët & Chandon' THEN '/images/Moet-Chandon.png'
    WHEN winery = 'Marchesi di Barolo' THEN '/images/marchesi.png'
    WHEN winery = 'Robert Mondavi' THEN '/images/robert-mondavi.png'
    WHEN winery = 'Ridge Vineyards' THEN '/images/ridge.png'
    WHEN winery = 'Tinhorn Creek' THEN '/images/tinhorncreek.png'
    WHEN winery = 'Concha y Toro' THEN '/images/conchaytoro.png'
    WHEN winery = 'Cloudy Bay' THEN '/images/cloudybay.png'
    WHEN winery = 'Catena Zapata' THEN '/images/Catena.png'
    WHEN winery = 'Cave Spring' THEN '/images/cavespring.png'
    WHEN winery = 'Chateau Ste. Michelle' THEN '/images/chateaustemichelle.png'
    WHEN winery = 'E. Guigal' THEN '/images/eguigal.png'
    WHEN winery = 'Clos Apalta' THEN '/images/closapalta.png'
    WHEN winery = 'Beringer' THEN '/images/beringer.png'
    WHEN winery = 'Ornellaia' THEN '/images/ornellaia.png'
    WHEN winery = 'Torres' THEN '/images/torres.png'
    WHEN winery = 'Villa Maria' THEN '/images/villa-maria.png'
    WHEN winery = 'Château Margaux' THEN '/images/chateau-margaux.png'
    WHEN winery = 'Louis Roederer' THEN '/images/louis-roederer.png'
    WHEN winery = 'Penfolds' THEN '/images/penfolds.png'
    WHEN winery = 'Jackson-Triggs' THEN '/images/jackson-triggs.png'
    WHEN winery = 'Inniskillin' THEN '/images/inniskillin.png'
    WHEN winery = 'Domaine de la Romanée-Conti' THEN '/images/Domaine.png'
    WHEN winery = 'Duckhorn' THEN '/images/Duckhorn.png'
    WHEN winery = 'Silver Oak' THEN '/images/silver-oak.png'
    WHEN winery = 'Château d''Yquem' THEN '/images/dyquem.png'
    WHEN winery = 'Château d''Esclans' THEN '/images/desclans.png'
    WHEN winery = 'Kistler' THEN '/images/kistler.png'
    WHEN winery = 'Tenuta San Guido' THEN '/images/tenutasanguido.png'
    WHEN winery = 'Ruinart' THEN '/images/ruinart.png'
    WHEN winery = 'Bollinger' THEN '/images/bollinger.png'
    WHEN winery = 'La Rioja Alta' THEN '/images/la-rioja-alta.png'
    WHEN winery = 'Domaine Leflaive' THEN '/images/domaine-leflaive.png'
    WHEN winery = 'Dominus Estate' THEN '/images/dominus-estate.png'
    WHEN winery = 'Krug' THEN '/images/krug.png'
    WHEN winery = 'Château Montelena' THEN '/images/montelena.png'
    WHEN winery = 'Domaine William Fèvre' THEN '/images/william-fevre.png'
    WHEN winery = 'Caymus Vineyards' THEN '/images/caymus.png'
    WHEN winery = 'Château Palmer' THEN '/images/palmer.png'
    WHEN winery = 'Opus One' THEN '/images/opus-one.png'
    WHEN winery = 'Gaja' THEN '/images/gaja.png'
    ELSE '/images/coming-soon.png'
END;




